packages:
  - packages/*
  - extensions/*
allowUnusedPatches: true
patchedDependencies:
  "18.x": "patches/clangd.patch"
  "@foxglove/wasm-bz2@*": "patches/@foxglove__wasm-bz2.patch"
  "@types/cacache@*": "patches/@types__cacache.patch"
  "ssh2@*": "patches/ssh2.patch"
  "vscode-languageclient@*": "patches/vscode-languageclient.patch"
  "@logtape/otel@*": "patches/@logtape__otel.patch"
catalog:
  "@biomejs/biome": 2.1.2
  "@formatjs/intl-durationformat": ^0.7.4
  "@foxglove/wasm-bz2": ^0.1.1
  "@githubocto/tailwind-vscode": ^1.0.5
  "@inlang/paraglide-js": 2.2.0
  "@leeoniya/ufuzzy": ^1.0.18
  "@logtape/logtape": ^1.0.4
  "@logtape/otel": ^1.0.4
  "@melt-ui/pp": ^0.3.2
  "@melt-ui/svelte": ^0.86.6
  "@opentelemetry/api": ^1.9.0
  "@opentelemetry/api-logs": ^0.203.0
  "@opentelemetry/auto-instrumentations-node": ^0.62.0
  "@opentelemetry/exporter-logs-otlp-grpc": ^0.203.0
  "@opentelemetry/exporter-logs-otlp-http": ^0.203.0
  "@opentelemetry/exporter-metrics-otlp-grpc": ^0.203.0
  "@opentelemetry/exporter-metrics-otlp-http": ^0.203.0
  "@opentelemetry/exporter-prometheus": ^0.203.0
  "@opentelemetry/exporter-trace-otlp-grpc": ^0.203.0
  "@opentelemetry/exporter-trace-otlp-http": ^0.203.0
  "@opentelemetry/otlp-exporter-base": ^0.203.0
  "@opentelemetry/resources": ^2.0.1
  "@opentelemetry/sdk-logs": ^0.203.0
  "@opentelemetry/sdk-metrics": ^2.0.1
  "@opentelemetry/sdk-node": ^0.203.0
  "@opentelemetry/sdk-trace-node": ^2.0.1
  "@opliko/ag-grid-svelte5-extended": ^0.0.15
  "@opliko/eventual-result": ^0.12.1
  "@opliko/vscode-js-profile-core": ^1.0.21
  "@opliko/vscode-js-profile-flame": ^1.0.32
  "@protobufjs/base64": ^1.1.2
  "@shikijs/transformers": ^3.8.1
  "@supercharge/promise-pool": ^3.2.0
  "@svelte-plugins/tooltips": 4.0.0-beta.1
  "@svelte-put/copy": 4.0.0
  "@sveltejs/adapter-static": ^3.0.8
  "@sveltejs/kit": ^2.25.1
  "@sveltejs/vite-plugin-svelte": 6.1.0
  "@tailwindcss/vite": ^4.1.10
  "@types/cacache": ^19.0.0
  "@types/chroma-js": ^3.1.1
  "@types/lodash-es": ^4.17.12
  "@types/mocha": ^10.0.10
  "@types/node": 24.0.14
  "@types/object-inspect": ^1.13.0
  "@types/sanitize-html": ^2.16.0
  "@types/semver": ^7.7.0
  "@types/ssh2": ^1.15.5
  "@types/stream-chain": ^2.1.0
  "@types/stream-json": ^1.7.8
  "@types/triple-beam": ^1.3.5
  "@types/vscode-webview": ^1.57.5
  "@valibot/to-json-schema": ^1.1.0
  "@vscode-elements/elements": 1.15.0
  "@vscode/codicons": ^0.0.38
  "@vscode/test-cli": ^0.0.11
  "@vscode/test-electron": ^2.5.2
  "@vscode/vsce": ^3.5.0
  "@zip.js/zip.js": ^2.7.64
  add: ^2.0.6
  ag-grid-community: ^34.0.2
  ajv: ^8.17.1
  autoprefixer: ^10.4.21
  cacache: ^19.0.1
  chokidar: ^4.0.3
  chroma-js: ^3.1.2
  comlink: ^4.4.2
  core-js: ^3.44.0
  corepack: ^0.33.0
  cpx: ^1.5.0
  dequal: ^2.0.3
  devtools-protocol: ^0.0.1488636
  domutils: ^3.2.2
  esbuild: ^0.25.6
  esbuild-plugin-cp: ^1.0.2
  esbuild-plugin-inline-import: ^1.1.0
  flourite: ^1.3.0
  htmlparser2: ^10.0.0
  json-stream-stringify: ^3.1.6
  ky: ^1.8.2
  lefthook: ^1.12.2
  llvm-project: github:llvm/llvm-project#release/18.x
  lodash-es: ^4.17.21
  lru-cache: ^11.1.0
  melt: ^0.38.0
  mocha: ^11.6.0
  node-ssh: ^13.2.1
  object-inspect: ^1.13.4
  p-debounce: ^4.0.0
  pathe: ^2.0.3
  pixi-viewport: ^6.0.3
  pixi.js: ^8.11.0
  plausible-tracker: ^0.3.9
  postcss: ^8.4.47
  quick-lru: ^7.0.1
  remove: ^0.1.5
  rimraf: ^6.0.1
  rollup-plugin-copy: ^3.5.0
  sanitize-html: ^2.17.0
  semver: ^7.7.2
  shiki: ^3.8.1
  shlex: ^2.1.2
  ssh-config: ^5.0.3
  ssh2: ^1.16.0
  stream-chain: ^3.4.0
  stream-json: ^1.9.1
  svelte: ^5.36.7
  svelte-check: ^4.3.0
  svelte-pixi: 8.0.0-next.2
  tailwindcss: ^4.1.10
  temporal-polyfill: ^0.3.0
  triple-beam: ^1.4.1
  tslib: ^2.8.1
  turbo: ^2.5.5
  typescript: ^5.8.3
  valibot: 1.1.0
  vite: ^7.0.5
  vscode-languageclient: ^9.0.1
  vscode-languageserver: 9.0.1
  vscode-languageserver-textdocument: 1.0.12
  winston: ^3.17.0
  winston-transport-vscode: ^0.1.0
  yaml: ^2.8.0
