[package]
authors = ["Marcin Glinski <m.glinski@samsung.com>"]
categories = ["parsing"]
description = "Read data from ftdb (.img) files"
edition = "2021"
keywords = ["ftdb", "mbsec", "ast"]
license-file = "LICENSE.md"
name = "ftdb"
version = "0.4.0"

[dependencies]
lazy_static = "1.4.0"
libc = "0.2.150"
thiserror = "1.0.50"

[dependencies.ftdb-sys]
path = "../ftdb-sys/"

[dev-dependencies]
# claim = "~0.5"
# pretty_assertions = "~1.3"
rstest = "0.18"

[features]
default = []
ftdb_verbose = []
stub = ["ftdb-sys/stub"]
