[package]
edition = "2021"
name = "callgraph"
version = "0.1.0"

[dependencies]
clap = {version = "4.5.1", features = ["derive"]}
ftdb = {path = "../../ftdb"}
ftdb-ext = {path = "../../ftdb-ext"}

[features]
default = []
