import QuickLRU from "quick-lru";
// `shiki/core` entry does not include any themes or languages or the wasm binary.
import { createHighlighterCore } from "shiki/core";
import { createJavaScriptRegexEngine } from "shiki/engine/javascript";

export const highlighter = createHighlighterCore({
	themes: [
		import("shiki/themes/dark-plus.mjs"),
		import("shiki/themes/dracula.mjs"),
		import("shiki/themes/github-dark.mjs"),
		import("shiki/themes/github-light.mjs"),
		import("shiki/themes/andromeeda.mjs"),
		import("shiki/themes/aurora-x.mjs"),
		import("shiki/themes/ayu-dark.mjs"),
		import("shiki/themes/catppuccin-frappe.mjs"),
		import("shiki/themes/catppuccin-latte.mjs"),
		import("shiki/themes/catppuccin-macchiato.mjs"),
		import("shiki/themes/catppuccin-mocha.mjs"),
		import("shiki/themes/dracula-soft.mjs"),
		import("shiki/themes/everforest-dark.mjs"),
		import("shiki/themes/everforest-light.mjs"),
		import("shiki/themes/github-dark-default.mjs"),
		import("shiki/themes/github-dark-dimmed.mjs"),
		import("shiki/themes/github-dark-high-contrast.mjs"),
		import("shiki/themes/github-light-default.mjs"),
		import("shiki/themes/github-light-high-contrast.mjs"),
		import("shiki/themes/houston.mjs"),
		import("shiki/themes/light-plus.mjs"),
		import("shiki/themes/material-theme-darker.mjs"),
		import("shiki/themes/material-theme-lighter.mjs"),
		import("shiki/themes/material-theme.mjs"),
		import("shiki/themes/material-theme-ocean.mjs"),
		import("shiki/themes/material-theme-palenight.mjs"),
		import("shiki/themes/min-dark.mjs"),
		import("shiki/themes/min-light.mjs"),
		import("shiki/themes/monokai.mjs"),
		import("shiki/themes/night-owl.mjs"),
		import("shiki/themes/nord.mjs"),
		import("shiki/themes/one-dark-pro.mjs"),
		import("shiki/themes/one-light.mjs"),
		import("shiki/themes/plastic.mjs"),
		import("shiki/themes/poimandres.mjs"),
		import("shiki/themes/red.mjs"),
		import("shiki/themes/rose-pine-dawn.mjs"),
		import("shiki/themes/rose-pine.mjs"),
		import("shiki/themes/rose-pine-moon.mjs"),
		import("shiki/themes/slack-dark.mjs"),
		import("shiki/themes/slack-ochin.mjs"),
		import("shiki/themes/snazzy-light.mjs"),
		import("shiki/themes/solarized-dark.mjs"),
		import("shiki/themes/solarized-light.mjs"),
		import("shiki/themes/synthwave-84.mjs"),
		import("shiki/themes/tokyo-night.mjs"),
		import("shiki/themes/vesper.mjs"),
		import("shiki/themes/vitesse-black.mjs"),
		import("shiki/themes/vitesse-dark.mjs"),
		import("shiki/themes/vitesse-light.mjs"),
	],
	langs: [
		import("shiki/langs/c.mjs"),
		import("shiki/langs/asm.mjs"),
		import("shiki/langs/cpp.mjs"),
		import("shiki/langs/cpp-macro.mjs"),
		import("shiki/langs/sh.mjs"),
		import("shiki/langs/bash.mjs"),
		import("shiki/langs/cmake.mjs"),
		import("shiki/langs/docker.mjs"),
		import("shiki/langs/dockerfile.mjs"),
		import("shiki/langs/rust.mjs"),
		import("shiki/langs/java.mjs"),
		import("shiki/langs/kotlin.mjs"),
		import("shiki/langs/protobuf.mjs"),
		import("shiki/langs/dotenv.mjs"),
		import("shiki/langs/python.mjs"),
		import("shiki/langs/perl.mjs"),
		import("shiki/langs/git-commit.mjs"),
		import("shiki/langs/git-rebase.mjs"),
		import("shiki/langs/ini.mjs"),
		import("shiki/langs/go.mjs"),
		import("shiki/langs/yaml.mjs"),
		import("shiki/langs/json.mjs"),
		import("shiki/langs/xml.mjs"),
		import("shiki/langs/ruby.mjs"),
	],
	engine: createJavaScriptRegexEngine({
		forgiving: true,
		cache: new QuickLRU({ maxSize: 100 }) as unknown as Map<
			string,
			RegExp | Error
		>,
	}),
});
