#!/usr/bin/env python3

import sys
import libetrace
import json

nfsdb = libetrace.nfsdb()
nfsdb.load(sys.argv[1],quiet=True)

# Getting all compilations for C files
comps = [e for e in nfsdb if e.has_compilations() and e.compilation_info.type==1]

def json_command(cmd):
	return json.dumps(" ".join([x.rstrip().replace("\\","\\\\").replace("\"","\\\"").replace(" ","\\ ") for x in cmd]))

json_vals = list()
cfs = set()
for e in comps:
	if e.compilation_info.files[0] not in cfs:
		json_vals.append( "{\"directory\":%s,\"command\":%s,\"file\":%s}"%(json.dumps(e.cwd),json_command(e.argv),json.dumps(e.compilation_info.files[0])) )
		cfs.add(e.compilation_info.files[0])
with open("compile_commands.json","w") as f:
	f.write(json.dumps(json.loads("[%s]"%",".join(json_vals)), indent=4, sort_keys=False))
print ("created compilation database file (compile_commands.json)")