[package]
authors = ["Marcin Glinski <m.glinski@samsung.com>"]
description = "Library to test ftdb (.img) files"
edition = "2021"
keywords = ["ftdb", "mbsec", "test"]
name = "ftdb-test"
version = "0.1.0"

[dependencies]
ftdb = { path = "../ftdb" }